# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: VariableGroup
  type: string
  default: itpeople-functions-test

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-20.04'

stages:
- stage: Build
  displayName: Build stage  
  
  jobs:
  # - job: BuildSolution
  #   displayName: Build Solution
  #   pool:
  #     vmImage: $(vmImageName)

  #   steps:
  #   - task: DotNetCoreCLI@2
  #     displayName: Build Solution
  #     inputs:
  #       command: build

  - job: PackageFunctionApp
    displayName: Package API Function App
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build API
      inputs:
        command: 'build'
        projects: src/API/API.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/ApiFunctionApp --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive API files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/ApiFunctionApp'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/ApiFunctionApp.zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/ApiFunctionApp.zip
      displayName: Publish API Web App Artifacts
      artifact: FunctionAppDrop

# - stage: Test
#   displayName: Test
#   dependsOn: Build
#   condition: succeeded()

#   jobs: 
#     - job: ApiTest
#       displayName: API Tests
#       pool:
#         vmImage: $(vmImageName)

#       steps:
#         - task: DotNetCoreCLI@2
#           displayName: Unit Tests
#           inputs:
#             command: test
#             projects: tests/API/Unit/Unit.csproj
            
#         - task: DotNetCoreCLI@2
#           displayName: Integration Tests
#           inputs:
#             command: test
#             projects: tests/API/Integration/Integration.csproj
  
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: DeployAPI
    displayName: Deploy API
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: Publish API Function App
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: '$(apiFunctionAppName)'
              package: '$(Pipeline.Workspace)/FunctionAppDrop/ApiFunctionApp.zip'
    
